### ISSUE TITLE
Rename `pathmod` / `PathModuleBase`

### ISSUE THREAD

**Issue by barneygale** [barneygale/pathlib-abc#19]
We now have an ABC for `PurePathBase.pathmod` called `PathModuleBase` - see https://pathlib-abc.readthedocs.io/en/latest/api.html#controlling-path-syntax

The naming here made sense for when `posixpath` and `ntpath` were the only possible values for `pathmod`, but with the addition of the `PathModuleBase` **class**, the "mod" bit isn't appropriate.

We should rename `pathmod` and `PathModuleBase`, hopefully before Python 3.13 beta 1 goes out.

**Comment by barneygale** [comment]
Tagging you @merwok in case this interests you or you have any suggestions/thoughts. Hope that's OK! Thanks.

**Comment by barneygale** [comment]
Name ideas: flavour, format, formatter, structure, manipulator, grammar

**Comment by merwok** [comment]
flavour, impl (for «object implementing operations»), manipulator

**Comment by barneygale** [comment]
> impl (for «object implementing operations»)

`PathModuleBase` only implements pure (lexical) operations, but if it's inherited into `Path` as `Path.impl`, I think it would incorrectly suggest that it's used to implement _all_ path functionality, including I/O.

**Comment by merwok** [comment]
Indeed, I thought it was doing that, like `accessor` used to.

I don’t think it’s very bad to have `pathmod`, especially if it names an object implementing a PathModuleBase ABC! If you feel that the names are misleading, both should be changed in agreement.

**Comment by ap--** [comment]
Hello everyone,

If I remember correctly from the thread on discuss.python.org the name pathmod was chosen because the posixpath and ntpath modules were the two options for the path 'flavours'.

To me personally, "format", "flavour", "syntax" or "parser" are more intuitive.

Cheers,
Andreas

**Comment by barneygale** [comment]
I like "flavour" tbh. Antoine used "flavour" in this way too when he wrote pathlib (I/O was done by the "accessor").

**Comment by merwok** [comment]
So `flavour` for a module with functions, or object with methods, and `PathFlavourBase` for the interface (is it an ABC?)

**Comment by barneygale** [comment]
Correct. Or just `FlavourBase`, I suppose.
