### ISSUE TITLE
License for pathlib_abc

### ISSUE THREAD

**Issue by Strider221B** [barneygale/pathlib-abc#22]
Hi,

We are using your package in one of our projects but we were not clear about the license terms of this package.

From the license document it seems it is a history of the license terms for Python from this page: https://docs.python.org/3/license.html
Can you please elaborate/confirm the exact terms of the license for this repo?

Is the code in the repo under [PSF License](https://docs.python.org/3/license.html#psf-license)?

If yes, can you please update the license document?

**Comment by barneygale** [comment]
It's licensed under the same terms as Python itself - https://github.com/python/cpython/blob/main/LICENSE

**Comment by barneygale** [comment]
Ah right I see what you mean! Thanks, will fix.
