### ISSUE TITLE
new version containing the changes from python 3.13.0b1 anytime soon?

### ISSUE THREAD

**Issue by kfot** [barneygale/pathlib-abc#24]
Hi, there are some new changes introduced in the `pathlib` module in the CPython [3.13 beta version](https://github.com/python/cpython/blob/v3.13.0b1/Lib/pathlib/_abc.py). Will they be released anytime soon as the new version of `pathlib_abc`? Thanks!

**Comment by barneygale** [comment]
Hi, I've now published 0.3.0. Ta!
